# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "App Store Connectへのビルド・アップロード・タグ付けの全自動化"
  lane :release do |options|
    # コマンド実行時に version:X.X.X が渡された場合のみバージョンを変更
    if options[:version]
      increment_version_number(
        version_number: options[:version],
        xcodeproj: "SakuttoSplit.xcodeproj"
      )
    end

    # 1. Xcodeプロジェクトのビルド番号を1繰り上げる
    increment_build_number(
      xcodeproj: "SakuttoSplit.xcodeproj"
    )

    # 2. アプリのアーカイブ・ビルド処理
    build_app(
      scheme: "SakuttoSplit",
      export_method: "app-store"
    )

    # 3. App Store ConnectへIPAファイルをアップロード
    upload_to_app_store(
      skip_metadata: true,
      skip_screenshots: true,
      force: true
    )

    # 4. バージョン情報を取得してGitコミット＆タグ作成
    version = get_version_number(xcodeproj: "SakuttoSplit.xcodeproj")
    build = get_build_number(xcodeproj: "SakuttoSplit.xcodeproj")
    
    git_commit(path: ".", message: "bump: Release v#{version} (#{build})")
    add_git_tag(tag: "v#{version}")
    push_to_git_remote
  end
end
